### PR TITLE
Changed "it's" to "its" in the License Agreement and other places

### PR DESCRIPTION
**Pull request by ianfixes**
A grammar mistake in the first window that the user sees seems unprofessional.

screen shot 2015-09-13 at 10 16 52 am

I patched the license text into terms I could accept.

### CODE REVIEW

**Comment by freaktechnik** [comment]
Looks good, thanks! The only thing we might or might not want to do is modify naturaldocs (which we don't use anyways, but it's in the tools folder), I'm not sure there.

**Comment by ianfixes** [comment]
Let me know when you know one way or the other.  Cherry-picking the first 2 commits should get you the most important stuff.

**Comment by rsjtdrjgfuzkfg** [comment]
Looks good to me as well. @freaktechnik agree on the naturaldocs thing; but we might consider removing it, or is there anything depending on that?!

**Comment by freaktechnik** [comment]
Natural docs was used to build the remote version of the Remote API docs, afaik, maybe @AntoineTurmel can confirm or deny that.

**Comment by freaktechnik** [comment]
Thanks for the patch! (and sorry for the delay in merging)

**Comment by ianfixes** [comment]
Glad to help :)

**Pull request merged**
