### PR TITLE
Added the tag %artistfl%

### PR DESCRIPTION
**Pull request by cybercox**
I have added the tag %artistfl%. This adds the ability to export music using a directory structure that handles the first artist-name's letter. I have developed this code since i needed to export my music to a SD card (to put it in my car) and exporting all the music to a single folder (or even the artist's name) produces a very slow performance (it seems that some devices do a complete read of the first level before start playing).
Through this little code you can specify the schema as:
%artistfl%/%artist%/%album%/%title%

### CODE REVIEW

**Comment by darealshinji** [comment]
There seem to be a lot of changes in this commit for just adding the %artistfl% tag. What happened there? Windows vs Unix end of line issue?

**Comment by freaktechnik** [comment]
Yeah, that looks like a linefeed conversion happened.

@cybercox could you point out the lines, with changes? There seem to be new strings for translation?

**Comment by darealshinji** [comment]
I've converted the format to Unix and created a diff: https://gist.github.com/darealshinji/22449d6a830ed21733c4

**Comment by rsjtdrjgfuzkfg** [comment]
@cybercox some comments:
- do not change the line endings of files (this is bad to read and destroys history).
- do proper indentation with two spaces. Do not use tabs.
- do not force english in non-english locale files (as we cannot automatically determine which parts are translated yet).
- why do you remove diacritics, and why is that the expected behaviour?
- [this stackoverflow post](http://stackoverflow.com/questions/990904/javascript-remove-accents-diacritics-in-strings) looks a lot like your code. Are you the person that posted it there? If not, can you please confirm you licensed that code in a way allowing you to include it into Nightingale without attributing the original author (as that is what your commit would do)?

@AntoineTurmel @freaktechnik imho we should move FolderSync locales to the core locales, or otherwise handle through our babelzilla (in contrast to my personal FolderSync entry in the old babelzilla, and migrate data from it).

**Comment by freaktechnik** [comment]
@rsjtdrjgfuzkfg Yeah, I agree on the locales part, the best way would probably be to add them to the normal ngale bundle, as we wouldn't have to set up syncing for another repo.

Also, I'm not sure if localizations break if a string is missing, because that's what happens, iirc.

**Comment by rsjtdrjgfuzkfg** [comment]
@freaktechnik yes, locales break if a string is missing. However, to upload stuff to babelzilla, only empty strings are properly marked as untranslated (at least on the old babelzilla, as you cannot determine if something is equal in a non-english language, or if the string was not yet translated).

**Comment by cybercox** [comment]
@rsjtdrjgfuzkfg and all the others: thanks for your comments!
1) i will make another fork without changing line delimiters
2) i will use proper indentation as suggested
3) i will leave blank untransalated strings 
4) i remove diatrics as i want to collapse "strange" letters to "simpler" ones. This is done as it's better to navigate the folder structure. imagine if you find in the same structure the dirs "e" "è" "é" and so on...
5) will change with some code released on MIT licence.

Thanks to all!!!

**Pull request closed without merging**
