### PR TITLE
Turn verbosity in Makefiles on/off

### PR DESCRIPTION
**Pull request by darealshinji**
Fixes https://github.com/nightingale-media-player/nightingale-hacking/issues/327.
Still needs to be tested on Windows and OSX.

### CODE REVIEW

**Comment by freaktechnik** [comment]
Works for me on Windows

**Comment by zjays** [comment]
This one also causes Mac building to break for me - here is the ending part of the terminal output: 

```
BUILDING installer TIER; directories: installer 


   GEN       LICENSE.html
   GEN       README_OFFICIAL.txt
cd /Users/Zach-Mac/github/nightingale-hacking/compiled/dist/Nightingale.app/Contents/Resources/components && @echo "       XPTLINK   link_installer_xpts";/Users/Zach-Mac/github/nightingale-hacking/dependencies/macosx-x86_64/mozilla-1.9.2/release/bin/xpt_link songbird.xpt browsercompsbase.xpt fuel.xpt ngEqualizerPresets.xpt ngInternalSearchEngines.xpt sbAlbumArt.xpt sbBrowserAPI.xpt sbBundle.xpt sbCDDevices.xpt sbClipboardHelper.xpt sbCommandLine.xpt sbController.xpt sbDataRemote.xpt sbDatabaseEngine.xpt sbDevice.xpt sbDeviceBase.xpt sbDeviceBase2.xpt sbDeviceController.xpt sbDeviceManager.xpt sbDeviceMarshall.xpt sbDirectoryImportService.xpt sbDisplayPanes.xpt sbDownloadDevice.xpt sbDragAndDrop.xpt sbFaceplate.xpt sbFeathers.xpt sbFileDownloader.xpt sbFileScan.xpt sbFileSystem.xpt sbFileUtils.xpt sbGStreamerMediacore.xpt sbIdentityServiceComponent.xpt sbImageParser.xpt sbIntegration.xpt sbIntl.xpt sbJob.xpt sbLibraryBase.xpt sbLibraryImporter.xpt sbLocalDatabaseLibrary.xpt sbMediaExportService.xpt sbMediaItemDownloadService.xpt sbMediaManager.xpt sbMediaPages.xpt sbMediacoreBase.xpt sbMediacoreErrorHandler.xpt sbMetadataHandlerTaglib.xpt sbMetadataLookup.xpt sbMetadataModule.xpt sbNetworkProxyImport.xpt sbPlayQueueService.xpt sbPlaybackHistoryService.xpt sbPlaylistCommands.xpt sbPlaylistReader.xpt sbPlaylistWriter.xpt sbPrompter.xpt sbProperties.xpt sbSQLBuilder.xpt sbSearchEngine.xpt sbServicePane.xpt sbStrings.xpt sbTemporaryFileService.xpt sbTestMediacoreBase.xpt sbTranscodeModule.xpt sbURIImportService.xpt sbURLFormatter.xpt sbUpdate.xpt sbWatchFolderService.xpt sbWebServicesLastFm.xpt sbWidgets.xpt sbWindowWatcher.xpt sbXPCOM.xpt sbiTunesImporter.xpt
/bin/sh: @echo: command not found
cd /Users/Zach-Mac/github/nightingale-hacking/compiled/dist/Nightingale.app/Contents/Resources/components && rm -f browsercompsbase.xpt fuel.xpt ngEqualizerPresets.xpt ngInternalSearchEngines.xpt sbAlbumArt.xpt sbBrowserAPI.xpt sbBundle.xpt sbCDDevices.xpt sbClipboardHelper.xpt sbCommandLine.xpt sbController.xpt sbDataRemote.xpt sbDatabaseEngine.xpt sbDevice.xpt sbDeviceBase.xpt sbDeviceBase2.xpt sbDeviceController.xpt sbDeviceManager.xpt sbDeviceMarshall.xpt sbDirectoryImportService.xpt sbDisplayPanes.xpt sbDownloadDevice.xpt sbDragAndDrop.xpt sbFaceplate.xpt sbFeathers.xpt sbFileDownloader.xpt sbFileScan.xpt sbFileSystem.xpt sbFileUtils.xpt sbGStreamerMediacore.xpt sbIdentityServiceComponent.xpt sbImageParser.xpt sbIntegration.xpt sbIntl.xpt sbJob.xpt sbLibraryBase.xpt sbLibraryImporter.xpt sbLocalDatabaseLibrary.xpt sbMediaExportService.xpt sbMediaItemDownloadService.xpt sbMediaManager.xpt sbMediaPages.xpt sbMediacoreBase.xpt sbMediacoreErrorHandler.xpt sbMetadataHandlerTaglib.xpt sbMetadataLookup.xpt sbMetadataModule.xpt sbNetworkProxyImport.xpt sbPlayQueueService.xpt sbPlaybackHistoryService.xpt sbPlaylistCommands.xpt sbPlaylistReader.xpt sbPlaylistWriter.xpt sbPrompter.xpt sbProperties.xpt sbSQLBuilder.xpt sbSearchEngine.xpt sbServicePane.xpt sbStrings.xpt sbTemporaryFileService.xpt sbTestMediacoreBase.xpt sbTranscodeModule.xpt sbURIImportService.xpt sbURLFormatter.xpt sbUpdate.xpt sbWatchFolderService.xpt sbWebServicesLastFm.xpt sbWidgets.xpt sbWindowWatcher.xpt sbXPCOM.xpt sbiTunesImporter.xpt
make -C .. stripsymbols
make -f /Users/Zach-Mac/GitHub/nightingale-hacking/compiled/Makefile do_stripsymbols 
Stripping package directory...
find /Users/Zach-Mac/github/nightingale-hacking/compiled/dist/Nightingale.app/Contents/Resources -type f -name "*.dylib" \
      -exec @echo "       STRIP     do_stripsymbols";strip -x -S {} \; 
find: -exec: no terminating ";" or "+"
strip: can't open file: {} (No such file or directory)
strip: can't open file: ; (No such file or directory)
make[6]: *** [do_stripsymbols] Error 1
make[5]: *** [stripsymbols] Error 2
make[4]: *** [export] Error 2
make[3]: *** [export_tier_installer] Error 2
make[2]: *** [tier_installer] Error 2
make[1]: *** [default] Error 2
make: *** [build] Error 2
```

**Comment by darealshinji** [comment]
`-exec @echo "       STRIP     do_stripsymbols";strip -x -S {} \;`

Yeah, that's not going to work. I wonder why it did work on Windows and Linux. Can you try if compiling with `make V=1` works on Mac?

**Comment by darealshinji** [comment]
In build/autodefs.mk.in:

```
STRIP = $(STRIP_V)@STRIP@
```

I guess I need to rework it then.

edit:
Should be fixed now (hopefully).

**Comment by zjays** [comment]
Thanks, mac building is fixed for me now!

**Pull request merged**
